cmake_minimum_required(VERSION 3.28)

option(USE_MODULES "Enable C++20 modules" OFF)
if(USE_MODULES MATCHES ON AND CMAKE_GENERATOR MATCHES "Ninja")
  message(STATUS "Enabling C++20 modules")
  set(CMAKE_CXX_SCAN_FOR_MODULES ON)
  set(CMAKE_EXPERIMENTAL_CXX_IMPORT_STD ON)
  if(CMAKE_CXX_COMPILER_IMPORT_STD)
    message(STATUS "List CMAKE_CXX_COMPILER_IMPORT_STD contains modules:")
    foreach(item ${CMAKE_CXX_COMPILER_IMPORT_STD})
      message(STATUS "-->${item}")
    endforeach()
  else()
    message(STATUS "No modules found in CMAKE_CXX_COMPILER_IMPORT_STD")
  endif()
else()
  message(STATUS "Disabling C++20 modules, set USE_MODULES=ON and use Ninja generator with Clang or GCC")
  set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
endif()
