# Check if mold is available on system
option(USE_MOLD "Use mold linker" OFF)
if(USE_MOLD)
  if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.29)
    find_program(MOLD_FOUND mold)
    if(MOLD_FOUND)
      set(CMAKE_LINKER_TYPE "MOLD")
      message(STATUS "Using linker [${CMAKE_LINKER_TYPE}]")
    else()
      message(FATAL "Mold not found")
    endif(MOLD_FOUND)
  else()
    message(FATAL_ERROR "CMake >= 3.29 required for CMAKE_LINKER_TYPE (mold support)")
  endif()
endif()
